### Register a new user
POST http://localhost:5000/signup
Content-Type: application/json

{
  "username": "milou",
  "email": "milou@mail.com",
  "password": "1234"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
  "credential": "milou@mail.com",
  "password": "1234"
}

### Logout
GET http://localhost:5000/logout

### Update playlist
PUT http://localhost:5000/playlist/18
Content-Type: application/json

{
  "id": "18",
  "name": "hello and gb",
  "description": " hello gdbye",
  "tracks": [
    {
      "trackId": 50,
      "spotify_id": "1Yk0cQdMLx5RzzFTYwmuld"
    },
    {
      "trackId": 51,
      "spotify_id": "2s5Kg7XPzPfMMHRS4zndUV"
    },
    {
      "trackId": 52,
      "spotify_id": "28LzmRnsiidhiBBUvdi6Aj"
    }
  ]
}